fix(web): fix double "fix production" button
satisfactory-factories/application pull request #301
Opened 2024-12-16 23:49 UTC by nils-keller-dev

Closes #240

2024-12-16 23:57 UTC, Maelstromeous commented on web/src/components/planner/products/Product.vue
>          ><i class="fas fa-wrench" /><span class="ml-1">Fix Production</span>
```suggestion
        ><i class="fas fa-wrench" /><span class="ml-1">Fix</span>
```

2024-12-17 00:03 UTC, Maelstromeous commented
Looks like there's a bug @nils-keller-dev:

<img width="1230" alt="Screenshot 2024-12-17 at 00 00 59" src="https://github.com/user-attachments/assets/4bf7a16b-1881-434a-a794-705d5d6e2ddb" />
<img width="813" alt="Screenshot 2024-12-17 at 00 01 02" src="https://github.com/user-attachments/assets/e6a8569b-ad2f-49a6-bd8e-41d73719c7b3" />

Repro:

1. Load Demo template
2. Look at Copper Basics
3. Note how wire is satisfied but it's being asked to be fixed, pressing on fix does nothing.

Also I think we can do this simplier. `factory.parts` all have parts with a `satisfied` key. It uses both internal product demands and export demands to create that value, so we should be able to just check if the part is satisfied as the condition of showing it.

Additionally, in the parts array, `amountRequired` is encompassing both internal production and external demands. It should be literally a matter of just making production match the `amountRequired` value.

2024-12-17 00:04 UTC, Maelstromeous requested changes
See above

2024-12-17 20:41 UTC, nils-keller-dev commented
> Also I think we can do this simplier. `factory.parts` all have parts with a `satisfied` key. It uses both internal product demands and export demands to create that value, so we should be able to just check if the part is satisfied as the condition of showing it.

So we don't need to check `factory.dependencies.metrics[id]?.difference`?


> Additionally, in the parts data, `amountRequired` is encompassing both internal production and external demands. It should be literally a matter of just making production match the `amountRequired` value.

That's what is happening in `fixProduction()`, right? So I don't need the extra logic regarding `fixExport()`?

2024-12-17 23:32 UTC, Maelstromeous commented
> So we don't need to check `factory.dependencies.metrics[id]?.difference`?

Don't think it's nessessary, no, it should be possible purely off amountRequired as that's a calculated value derived from the other demand sources (production, exports)

> That's what is happening in `fixProduction()`, right? So I don't need the extra logic regarding `fixExport()`?

I believe that's the case yes, requires testing naturally.

2025-01-09 20:11 UTC, Maelstromeous commented
Related #299

2025-01-09 20:55 UTC, merged